name: Code Build and MY SQL Database update

on:
  push:
    branches:
      - JavaMySQLdb
    paths:
    - readmejavamysql.md 

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
       java-version: 14
        
    - name: Build and test project with Maven
      run: sudo mvn -B package --file pom.xml
  
  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 14
        - run: sudo mvn -B package --file pom.xml -DskipITs --settings ./maven/settings.xml
        - run: docker build src -t vijaygithubregistry.azurecr.io/webmysqlhol:latest
        
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.ACTIONSDEPLOY }}

        - uses: azure/docker-login@v1
          with:
            login-server: vijaygithubregistry.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            
        - run: docker push vijaygithubregistry.azurecr.io/webmysqlhol:latest
                 
     
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'vijayjavamysql'
            images: 'vijaygithubregistry.azurecr.io/webmysqlhol:latest'
  
  mysqlupdate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ACTIONSDEPLOY }}
   
    - uses: azure/mysql@v1
      with:
        server-name: vijayjavamysqlhol.mysql.database.azure.com
        connection-string: ${{ secrets.MYSHUTTLECONNECTION }}
        sql-file: './CreateMYSQLDB.sql'
